name: "Deploy"
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: 192730322953.dkr.ecr.us-west-2.amazonaws.com
      REPOSITORY: progate_lion_hackathon
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v31

      - uses: aws-actions/configure-aws-credentials@v4
        with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

      - name: build and push Docker image to ECR
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}