name: "Deploy and Trigger ArgoCD"

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: 192730322953.dkr.ecr.us-west-2.amazonaws.com
      REPOSITORY: alive-talk
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to ECR
        working-directory: ./backend
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}

  update-manifest:
      runs-on: ubuntu-latest
      needs: build-and-push
      env:
        REGISTRY: 192730322953.dkr.ecr.us-west-2.amazonaws.com
        REPOSITORY: alive-talk
        IMAGE_TAG: ${{ github.sha }}
      steps:
        - name: Generate GitHub App Token
          id: generate_token
          uses: tibdex/github-app-token@v2
          with:
            app_id: ${{ secrets.APP_ID }}
            private_key: ${{ secrets.PRIVATE_KEY }}
  
        - name: Checkout Kubernetes manifest repository
          uses: actions/checkout@v3
          with:
            repository: yomi4486/alive_talk_k8s_manifest
            ref: main
            token: ${{ steps.generate_token.outputs.token }}
  
        - name: Update image tag in Kubernetes manifests
          run: |
            yq -i '.spec.template.spec.containers[] |= select(.name == "progate-lion-hackathon-app").image = strenv(REGISTRY) + "/" + strenv(REPOSITORY) + ":" + strenv(IMAGE_TAG)' ./manifests/deployment.yml
        - name: Commit and push updated manifests
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
            git push
        
#        - name: Install kubectl
#          uses: azure/setup-kubectl@v4
#
#        - name: Install ArgoCD
#          run: |
#            sudo apt update
#            curl -sSL -o /usr/local/bin/kubectl https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
#            chmod +x /usr/local/bin/kubectl
#            curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
#            chmod +x argocd-linux-amd64
#            sudo mv argocd-linux-amd64 /usr/local/bin/argocd
#
#        - name: Configure kubectl for EKS
#          run: |
#            aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name alive-talk
#  
#        - name: Login to ArgoCD
#          run: |
#            argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
#  
#        - name: Sync application in ArgoCD
#          run: |
#            argocd app sync alive-talk